import Image from "next/image";
import Head from "next/head";
import styles from "./Developers.module.css";
import Navigation from "../Layout/Navigation";
import GabrielImg from "../../public/assets/images/gabriel.webp";
import NicolasImg from "../../public/assets/images/Profile.webp";
import TeamsLogo from "../../public/assets/images/team.webp";

const Developers = () => {
  return (
    <>
      <Head>
        <title>JS TEAM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <main className="p-5 flex flex-col justify-center items-center">
        <h2 className="text-primary-text text-6xl font-semibold">
          Nuestro Equipo
        </h2>

        <p className="text-xl mt-5">
          Somos un equipo apasionado que se divierte construyendo tus sueños
        </p>

        <div className="mt-10">
          <div className={styles.grid}>
            <a href="https://github.com/Nicolas-pc-dev" className={styles.card}>
              <h2>Nicolas</h2>
              <Image
                src={NicolasImg}
                alt="nicolas Profile"
                width={150}
                height={150}
              />
              <p>
                Frontend <br></br> Developer
              </p>
              <hr></hr>
            </a>

            <a
              href="https://github.com/gabrielcontrerasv"
              className={styles.card}
            >
              <h2>Gabriel</h2>
              <Image
                src={GabrielImg}
                alt="gabriel profile"
                width={150}
                height={150}
              />
              <p>
                Backend <br></br> Developer
              </p>
              <hr></hr>
            </a>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.teaminternational.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <Image src={TeamsLogo} alt="Team Logo" width={72} height={60} />
        </a>
      </footer>
    </>
  );
};

export default Developers;
